주식 페이지 업데이트 및 관심종목 공용 컴포넌트 업로드
nine-specs/next14-nine-specs pull request #35
Opened 2024-07-09 11:48 UTC by gitjoyoung

- 공용
 1 .관심종목 컴포넌트
src\components\Report\FavorStockList\FavorStockList.tsx에 위치해 있습니다 

- report 페이지
env.local에서 환경 상수를 변경하였습니다
```
LOCAL_API_URL= http://localhost:3000

LLAMA_USER_ID= sfacspace_4
LLAMA_USER_PW= Bwl9SrmXHt2x

LLAMA_TOKEN_URL= http://43.203.238.76:8000/auth/token
LLAMA_REPLY_URL= http://43.203.238.76:8000/generate
``` 

혹시 report 페이지 접속이 잘되나 한번 확인 해주시면 좋을것 같습니다
그리고 주식 api 가 네이버 api라 클라이언트 페이지에서도 cors 오류가 안뜰 것 같아요
굳이 api로 분리를 안해도 아마도 통신이 될 것으로 생각되네요
src\service\report\stockDetailsApi.ts

2024-07-09 12:56 UTC, danggin approved these changes

2024-07-10 00:48 UTC, helloleesul requested changes

2024-07-10 00:49 UTC, gitjoyoung commented on src/common/Chatbot/ChatForm.tsx
> +            <MessageBox key={uuid()} {...message} />
확인했습니다

2024-07-10 00:55 UTC, gitjoyoung commented on src/components/Report/FavorStockList/FavorStockList.tsx
> +          <div className="w-[387px] mb-3" key={uuid()}>
해당 키값을 다른 컴포넌트와 중복 되서 사용될 수 있는 여지가 있기 때문에 사용하였는데 
이부분은 상의통해 결정 하면 좋을 것 같습니다.

2024-07-10 08:52 UTC, closed without merging

2024-07-10 08:52 UTC, gitjoyoung commented
타 컴포넌트 수정으로 깃 하드 리셋 하였습니다